#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libetonyek
Version  : 0.1.8
Release  : 1
URL      : https://dev-www.libreoffice.org/src/libetonyek-0.1.8.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libetonyek-0.1.8.tar.xz
Summary  : Library for parsing Apple Keynote file format structure
Group    : Development/Tools
License  : MPL-2.0-no-copyleft-exception
Requires: libetonyek-bin
Requires: libetonyek-lib
Requires: libetonyek-license
BuildRequires : boost-dev
BuildRequires : doxygen
BuildRequires : glm-dev
BuildRequires : mdds-dev
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(liblangtag)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(zlib)
BuildRequires : sed

%description
libetonyek is a library and a set of tools for reading and converting
Apple iWork documents (Keynote, Pages and Numbers). Supported versions
are Keynote 2-6, Pages 1-4 and Numbers 1-2. See FEATURES for more
details about what is currently supported.

%package bin
Summary: bin components for the libetonyek package.
Group: Binaries
Requires: libetonyek-license

%description bin
bin components for the libetonyek package.


%package dev
Summary: dev components for the libetonyek package.
Group: Development
Requires: libetonyek-lib
Requires: libetonyek-bin
Provides: libetonyek-devel

%description dev
dev components for the libetonyek package.


%package doc
Summary: doc components for the libetonyek package.
Group: Documentation

%description doc
doc components for the libetonyek package.


%package lib
Summary: lib components for the libetonyek package.
Group: Libraries
Requires: libetonyek-license

%description lib
lib components for the libetonyek package.


%package license
Summary: license components for the libetonyek package.
Group: Default

%description license
license components for the libetonyek package.


%prep
%setup -q -n libetonyek-0.1.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534630003
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534630003
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libetonyek
cp COPYING %{buildroot}/usr/share/doc/libetonyek/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/key2raw
/usr/bin/key2text
/usr/bin/key2xhtml
/usr/bin/numbers2csv
/usr/bin/numbers2raw
/usr/bin/numbers2text
/usr/bin/pages2html
/usr/bin/pages2raw
/usr/bin/pages2text

%files dev
%defattr(-,root,root,-)
/usr/include/libetonyek-0.1/libetonyek/EtonyekDocument.h
/usr/include/libetonyek-0.1/libetonyek/libetonyek.h
/usr/lib64/libetonyek-0.1.so
/usr/lib64/pkgconfig/libetonyek-0.1.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libetonyek/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libetonyek-0.1.so.1
/usr/lib64/libetonyek-0.1.so.1.0.8

%files license
%defattr(-,root,root,-)
/usr/share/doc/libetonyek/COPYING
